Bismuth-Forge/bismuth

.husky/pre-commit, CONTRIBUTING.md, package.json, test/tilelayout.spec.js
=> Add pre commit hooks

.github/workflows/master.yml
=> ci: add qmllint action

README.md, bin/install.sh
=> fix: check plugin info after installation

src/controller/index.ts, src/driver/index.ts, src/engine/engine_context.ts, src/engine/index.ts, src/index.ts
Both are using the controller as a mediator.
=> Driver and engine are breaking up

README.md, img/demo.gif.license
=> Provide quick script showcase

README.md
Add Wayland badge. Change prettier one a bit.
=> docs: :memo: update badges

src/controller/action.ts
I've made a mistake, when was refactoring. Nice.
0. `npm run script-install` & relaunch KWin if on x11
1. Assign shortcut to "Toggle quarter layout"
2. Execute it
3. Layout should be changed to Quarter.
Closes #68
=> fix: :bug: use correct quarter layout id

.github/workflows/master.yml
Super Linter didn't work properly, because I forgot to set config variable for typescript.
Ref #70
=> Enable linting for TypeScript files

.eslintrc.json, package.json
This should enable formatting linting errors in the CI.
Closes #70
=> ci: :construction_worker: add prettier eslint plugin

.github/workflows/release-please.yml
Create release please action
Ref #1
=> ci: :construction_worker: release please action

package.json
=> chore: :bookmark: increment version

README.md
Add quick installation instructions.
The following should work only if we have any releases ready.
1. Run the script in the README.
2. Script should be successfully installed.
Ref #66
=> fix: :memo: add simple installation instructions

CHANGELOG.md, contrib/quick-install.sh
Title. Script is chore and not part of release (feat:), since it needs to be in the master.
1. Run contrib/quick-install.sh
2. Script should be installed
Ref #66
=> chore: fixes changelog, provides quick installation script

README.md, contrib/quick-install.sh, res/install.sh
This provides installation instructions in the README file.
1. Follow the installation instructions
3. Latest script release should be installable
Closes #66
=> Provide simple installation instuctions for the end user

README.md
Added a link to the AUR package in Installation section of the README
=> Add AUR as an install method

scripts/sysdep-install.sh
=> feat: add Manjaro to the sysdep-install.sh script

README.md
I am currently mainting an ebuild for packging in Gentoo. It may be useful to other users.
Using release artifacts as requested in #152
=> Add Gentoo

.github/workflows/master.yml
This should fix the recent breakage in the CI.
=> chore: pin super linter version

CONTRIBUTING.md, README.md, ROADMAP.md
Added roadmap and some minor improvements (see commits).
=> Docs improvements

src/kwinscript/engine/index.ts
When bismuth finds two windows are equally distanced from the current
window, the last used window will be chosen when focus is moved via
keyboard shortcuts.
Before, the closest windows were always determined based on the top-left
corner of each window. This is fine when focusing a window below or to
the right, since adjacent edge aligned windows will have the top-left
corner on the same line either horizontally or vertically.
When moving the focus up or to the left, however, this is no longer
guaranteed. Even though the bottom of two candidate windows might be
edge to edge with the current window, the top-left corners might be on
different levels since the candidate windows don't have to have the same
height. To correctly select the last used adjacent edge aligned window
to the top or to …
=> fix: select last used window when moving focus up or to the left

src/kwinscript/controller/action.ts, src/kwinscript/controller/index.ts, src/kwinscript/engine/layout/spiral_layout.ts
Reference to Issue #106, added keyboard shortcut entry for spiral layout.
Closes #106
=> Add Shourcut entry for Spiral Layout

scripts/sysdep-install.sh
=> chore: add gcc compiler to sysdep-install script

README.md
=> chore: add donation link

contrib/README.md
=> chore: fix the window border instructions

CMakeLists.txt, src/config/bismuth_config.kcfg, src/config/kconf_update/CMakeLists.txt, src/config/kconf_update/new_logger.upd, src/core/CMakeLists.txt, src/core/qml-plugin.cpp, src/core/ts-proxy.cpp, src/core/ts-proxy.hpp, src/kwinscript/config.ts, src/kwinscript/controller/index.ts, src/kwinscript/extern/proxy.d.ts, src/kwinscript/index.ts, src/kwinscript/ui/main.qml, src/kwinscript/util/log.ts
Replace the TS logger with the native one from the Qt.
Debug enabled option is now gone, since it is not needed anymore.
=> Move logging into core

.github/scripts/sysdep-install.sh, .pre-commit-config.yaml, CMakeLists.txt, README.md, contrib/README.md, scripts/sysdep-install.sh, src/CMakeLists.txt, src/config/kconf_update/CMakeLists.txt, src/core/CMakeLists.txt, src/core/plasma-api/CMakeLists.txt, src/kcm/CMakeLists.txt, src/kcm/icons/CMakeLists.txt, src/kdecoration/CMakeLists.txt, src/kdecoration/decoration.cpp, src/kdecoration/decoration.hpp, src/kdecoration/metadata.json, src/kwinscript/CMakeLists.txt, src/kwinscript/icons/CMakeLists.txt, src/kwinscript/kconf_update/CMakeLists.txt, tests/core/CMakeLists.txt, tests/core/plasma-api/CMakeLists.txt
This adds a new window decoration, that wraps the window with a colorful border with configurable width.
The color of the window depends on the color scheme and accent color.
1. Open window decorations KCM module and select the new decoration.
2. Change the active window state by focusing windows. 
3. Change the colors in the Colors KCM.
4. Change the border width within the window decorations KCM.
5. All the changes should be applied and work.
Closes #247
=> Add border-only window decoration

README.md
=> chore: add official ubuntu repo to the packages list

scripts/sysdep-install.sh
=> chore: add kglobalaccel dev env script

CMakeLists.txt
Just fixed a small typo in the CMakeLists.txt (Compler -> Compiler).
Do your changes intentionally break something on the user side or configuration? Absolutely not.
| Use TypeScript Compler to check | Use TypeScript Compiler to check |
Ran cmake again and it worked the same. It's just a one-letter typo fix.
Closes #X
=> Fix a typo
