README.md, contrib/import_krohnkite.sh
This change adds a bash script, that moves the old Krohnkite shortcuts to Bismuth ones (i.e. imports them).
1. Copy the shortcuts' configuration from "~/.config/kglobalshortcutsrc" to a file. The file must contain definitions for both Krohnkite and Bismuth
2. Execute the new script with the absolute path to this script: `contrib/import_krohnkite.sh $PWD/shortcuts_test_file`
3. Shortcuts from Krohnkite should be deleted and the bismuth ones should contain the definitions from previous Krohnkite shortcuts.
4. Given that the Bismuth script was already running, you should be able to use new shortcuts.
Closes #26
=> feat: :sparkles: add Krohnkite shortcuts import script

README.md, src/controller/action.ts
Change the default keys from Meta + I and Meta + D to avoid conflicting with Meta + D shortcut.
No breaking changes. Users of the existing shortcut will not be affected.
Relates to #41
=> feat: :wrench: new master area window count shortcuts

.github/workflows/release-please.yml
This modifies release please workflow, so that the packages (kwinscript and the quick-install archive) will be published, when a new release is created.
Tested on https://github.com/gikari/test-bismuth-ci
Ref #1
=> ci: 👷 publish artifacts on release

contrib/import_krohnkite.sh
Use correct key from the old configuration.
1. Run contrib/imprort_krohnkite.sh
2. Tile layout shortcut should be imported
Ref #90
=> fix: :bug: correctly import Tile Layout Krohnkite shortcut

src/kwinscript/engine/layout/quarter_layout.ts
Simple bugfix
None
None
1. Reload Script...
2. Put two windows side by side in quarter tiling
3. Both windows in quarter tiling should resize proprely
Closes #135
=> fix: do not ignore second windows when resize

.github/scripts/tar-build.sh, .github/workflows/release-please.yml
Produce build artifacts after release and attach them to the GitHub release page. This helps packagers - they don't have to use NPM.
Tested with another repo: https://github.com/gikari/test-bismuth-ci/releases/tag/v3.0.0
Ref #152
=> chore: publish build artifacts on release

src/kwinscript/config.ts
1. Add a rule for the window, that will end with a comma, or will contain an empty string. Apply the settings.
2. Tiling should not be broken
Closes #154
=> fix: prevent broken tiling, by not including empty stings into rules

.editorconfig
Also sets the default character set to UTF-8 and 4 space indentation. Files included in the second block will have 2 space indentation.
Note: Currently, all the QML files have 4 space indentation. I am not sure if that's intentional, thus I haven't removed the `*.qml` pattern.
=> chore: remove file specific rules from the .editorconfig

README.md, src/kwinscript/controller/action.ts, src/kwinscript/controller/index.ts, src/kwinscript/engine/layout/tile_layout.ts
Adds a shortcut for rotating the layout in a reversed direction. Unbound by default.
=> feat: add a shortcut for the reverse rotation action

scripts/install.sh, src/kcm/bismuth_config.kcfg, src/kcm/package/contents/ui/Behaviour.qml, src/kcm/package/contents/ui/main.qml
Now the behavior tab is the first, as the important option is here. We could enable script by default, but this will result in a potentially unpleasant surprise for the end user ("I installed the package, why is everything got wonky?"). When the user enables the tiling explicitly, they get the answer to this question more intuitively and will be immediately presented with an option to disable it, if something goes wrong ("Oh, I enabled the script, windows got places, that's why. Maybe it's not that great, I will disable the tiling then"),
| ![Screenshot_20211110_182938](https://user-images.githubusercontent.com/14205339/141142218-66729217-7b51-48cd-87e8-657a …
=> Enable/disable script from the KCM

LICENSES/LGPL-3.0-or-later.txt, src/kcm/icons/22-categories-bismuth-kcm.svg, src/kcm/icons/64-categories-bismuth-kcm.svg, src/kcm/icons/CMakeLists.txt, src/kcm/package/metadata.desktop
Replaces KCM icon with something more suitable. 
Based on the Breeze icon theme:
https://develop.kde.org/frameworks/breeze-icons
| ![before_dark](https://user-images.githubusercontent.com/28950897/141324133-8c50c1c5-8612-4b0d-ad92-dccb706d5bbb.png) | ![dark](https://user-images.githubusercontent.com/28950897/141323507-6ae5df60-49e8-4114-8c4a-082c4525c323.png) |
=> chore: replace KCM icon

src/kwinscript/CMakeLists.txt, src/kwinscript/icons/32-status-bismuth-column.svg, src/kwinscript/icons/32-status-bismuth-floating.svg, src/kwinscript/icons/32-status-bismuth-monocle.svg, src/kwinscript/icons/32-status-bismuth-quarter.svg, src/kwinscript/icons/32-status-bismuth-spiral.svg, src/kwinscript/icons/32-status-bismuth-spread.svg, src/kwinscript/icons/32-status-bismuth-stair.svg, src/kwinscript/icons/32-status-bismuth-tile.svg, src/kwinscript/icons/CMakeLists.txt
Adds an icon to the OSD popup that appears when switching layouts.
| ![before](https://user-images.githubusercontent.com/28950897/140795856-86fb2b25-4349-478e-9ced-6fb83d90d945.jpg) | ![after](https://user-images.githubusercontent.com/28950897/140795901-63d54ae5-bbdb-4885-ae80-aee7dec66b5c.gif) |
1. Reinstall Bismuth.
2. Restart KWin.
3. Switch between layouts.
Closes #129
=> feat: add custom icons for the OSD popup

src/kwinscript/CMakeLists.txt
This way the qml files would be automatically up to date
and would not require the rebuild.
=> chore: add depends clause to ui build rule

src/kwinscript/metadata.desktop
Hides the script entry in the system settings' "KWin Scripts" tab.
Closes #191
=> fix: hide the script entry in the system settings

src/kwinscript/CMakeLists.txt
This fixes the issue, when you change come `.ts` files, but the generated `index.mjs` is still old.
=> chore: add TS sources to build system

src/kwinscript/controller/index.ts, src/kwinscript/driver/index.ts, src/kwinscript/engine/index.ts, src/kwinscript/engine/layout/cascade_layout.ts, src/kwinscript/engine/layout/floating_layout.ts, src/kwinscript/engine/layout/index.ts, src/kwinscript/engine/layout/monocle_layout.ts, src/kwinscript/engine/layout/quarter_layout.ts, src/kwinscript/engine/layout/spiral_layout.ts, src/kwinscript/engine/layout/spread_layout.ts, src/kwinscript/engine/layout/stair_layout.ts, src/kwinscript/engine/layout/three_column_layout.ts, src/kwinscript/engine/layout/tile_layout.ts, src/kwinscript/extern/global.d.ts, src/kwinscript/ui/main.qml, src/kwinscript/ui/popup.qml
Adds two optional parameters to the `showNotification` function:
- `icon` - name of the icon, which should be displayed in the popup.
- `hint` - right-aligned text, used to display the number of master windows in some layouts.
Required for #176.
=> fix: provide a backend for custom icons in the OSD popup

scripts/sysdep-install.sh
I was trying to install this in KDE neon and the dependency installation script doesn't work. While I could manually run this, I think it would be easy for KDE Neon users to have it run directly like this. 
Summary of the pull request.
Do your changes intentionally break something on the user side or configuration?
| Screenshot of UI before change | Screenshot of UI after change |
1. Reload Script...
2. ...
3. Something happens
Closes #X
=> Add KDE Neon to the sysdep-install.sh

src/kwinscript/engine/window.ts
Apparently pressing the maximize button doesn't actually force the
window into any specific geometry. This resulted in windows staying in their
tiled geometry while all other windows would be rearranged as if the
maximized window would be floating.
This fix makes the maximized window fill the entire working area.
1. Install PR version of script
2. Open two or more windows
3. Maximize one of the windows (via titlebar button or `Alt + F3` menu)
4. Watch window take up the whole working area
Closes #101
=> fix: properly maximize windows via window decoration buttons

src/kwinscript/engine/index.ts
Before, when no window was focused, focusing a window with keyboard
shortcuts would only work if there were two or more windows visible. It
would also only consider tiled windows at all.
Now, any window, floating or tiled, is considered when no window was
focused previously.
1. Install PR version of script
2. Open a single (floating) window
3. Unfocus the single window (click somewhere outside the floating window)
4. Use any focus window shortcut (e.g. Focus Upper Window; default `Meta + j`)
5. Observe how the single visible window gets focus
=> fix: focus lone window with move focus shortcut

CMakeLists.txt, src/kwinscript/CMakeLists.txt
Moves the code used for determining project version to the root CMakeList file. That's because `CMAKE_PROJECT_VERSION` variable will be required for the applet as well.
=> chore: set the project version in the top cmake file

src/kwinscript/engine/index.ts
When doing the refactoring for #209, I seem to have mixed up some of the logic that wasn't caught during testing. Fixed it here.
When moving up, the closest window should be the lowest of all candidates and thus have the greatest y-coordinate. (The coordinate 0,0 is in the top-left corner and greater y-coordinates mean the window is further *down*.) Therefore it is necessary to use the `max()` function in this case instead of `min()`. In this case the starting value cannot be `Infinity` as that would always be the greatest value and not provide any useful result.
*Maybe* #221. I can't reproduce that issue either and actually found this regression independently while working on #210.
=> fix: use correct min/max func and start val for finding closest window

README.md
I'm currently maintaining a rpm build of bismuth for my personal use, so I decided to polish it a little and publish it on the Copr. This is my first time packaging in fedora and rpm so it might not be ideal but it works fine for me in fedora 35.
I took the build dependencies from `scripts/sysdep-install.sh`.
The SPEC file is hosted on my github https://github.com/JCapucho/fedora-rpms
Link to the copr https://copr.fedorainfracloud.org/coprs/capucho/bismuth/
=> Add fedora package

README.md
Also added a period after the Fedora Copr for uniformity
Add Debian/Ubuntu package
This will work on the following releases.
Debian stable/bullseye
Debian testing/bookworm
Debian unstable/sid
Ubuntu 21.04+
Unfortunately it seems maybe plasma is too old for Ubuntu 20.04.
=> Add Debian/Ubuntu package

README.md
I think it would be useful to create a matrix room, where people could ask quick questions and discuss the extension. 
The chat is hosted on KDE Matrix server.
#262
=> chore: add matrix room

src/kwinscript/CMakeLists.txt
Fixes the following message:
> 🏗️ Compiling and bundling **TypeScirpt** sources...
Untested since I'm new to Bismuth, and it's only a comment. I hope this doesn't annoy you too much. :)
=> fix typo: "TypeScirpt"

README.md
Adds Solus to the list of distros in README.md.
Package: https://dev.getsol.us/source/bismuth
I can't decide what is best to use as the link text because, unlike all the other distributions, the package is in the official repo (which is just called 'Solus' in eopkg, the package manager).
=> Add Solus to distributions list

src/kwinscript/driver/window.ts, src/kwinscript/extern/kwin.d.ts
Mark transient windows as utility windows and make them float instead of making them tiled
None
None
1. Reload Script...
2. Utility windows such as polkit windows should not be tiled
Some windows are however not marked as transient for some obscure reasons and are still tiled.
Partially closes #115
=> Make most of utility windows float on wayland

scripts/build.sh, scripts/test.sh, src/core/CMakeLists.txt, src/core/plasma-api/client.cpp, src/core/plasma-api/client.hpp, src/core/plasma-api/plasma-api.cpp, src/core/plasma-api/plasma-api.hpp, src/core/plasma-api/toplevel.cpp, src/core/plasma-api/toplevel.hpp, src/core/plasma-api/workspace.cpp, src/core/plasma-api/workspace.hpp, tests/core/CMakeLists.txt, tests/core/plasma-api/CMakeLists.txt, tests/core/plasma-api/workspace.cpp
Actually, a bunch of stuff:
- Tests were moved into the separate binary
- API now wraps around QObject* KWin implementation pointers and not QJSValues.
- API is tested against context properties and not JS globalObject. The latter does not work in the QML KWin scripts.
This was tested by connecting the new signal to a lambda with a log. So far it works.
=> Add signal forwarding for Plasma (KWin) API

src/config/bismuth_config.kcfg
Since zoom makes its popups with wrong WM props, it's a good candidate
for the default ignore list.
Closes #274
=> fix: add zoom windows to the default ignore list

scripts/optimize-icons.sh, src/kcm/icons/22-categories-bismuth-kcm.svg, src/kcm/icons/64-categories-bismuth-kcm.svg, src/kcm/icons/sc-apps-bismuth.svg, src/kwinscript/icons/16-status-bismuth-column.svg, src/kwinscript/icons/16-status-bismuth-floating.svg, src/kwinscript/icons/16-status-bismuth-monocle.svg, src/kwinscript/icons/16-status-bismuth-quarter.svg, src/kwinscript/icons/16-status-bismuth-spiral.svg, src/kwinscript/icons/16-status-bismuth-spread.svg, src/kwinscript/icons/16-status-bismuth-stair.svg, src/kwinscript/icons/16-status-bismuth-tile.svg, src/kwinscript/icons/32-status-bismuth-column.svg, src/kwinscript/icons/32-status-bismuth-floating.svg, src/kwinscript/icons/32-status-bismuth-monocle.svg, src/kwinscript/icons/32-status-bismuth-quarter.svg, src/kwinscript/icons/32-status-bismuth-spiral.svg, src/kwinscript/icons/32-status-bismuth-spread.svg, src/kwinscript/icons/32-status-bismuth-stair.svg, src/kwinscript/icons/32-status-bismuth-tile.svg, src/kwinscript/icons/CMakeLists.txt
Optimizes all SVG icons using scour. Adds a bash script for optimizing any future icons. 
Also adds 16px version of layout icons (to be used in applet's context menu):
This shouldn't change the appearance of any icon.
=> refactor: optimize svg icons

.github/workflows/docs.yml, .github/workflows/master.yml, CONTRIBUTING.md, Makefile, package.json
This makes it possible to name targets whatever we want and makes us
less dependent on the NPM (i.e. a preparation for NPM removal).
=> chore: move npm scripts to makefile

src/kdecoration/decoration.cpp
Capture this by value, check painter for nullness.
Make sure, that the linked bug is not reproducible after a change.
Closes #332
=> fix(kdecoration): prevent crash when changing color scheme

src/core/CMakeLists.txt, src/core/kconf_update/CMakeLists.txt, src/core/kconf_update/legacy_shortcuts.cpp, src/core/kconf_update/legacy_shortcuts.hpp, src/core/qml-plugin.cpp
kconf_update script wasn't working, so this new implementation is using
the KGloablAccel directly and before setting the new shortcuts.
This implementation should fix the user's issues for good.
1. Make that, you have your legacy KWin shortcuts regirstered
1. Reload Script.
2. Old shortcuts should disappear and new ones should be listed.
Closes #336
=> fix: move old shortcuts to the new component correctly

src/core/ts-proxy.cpp
This should not put the spaces in the comma separated lists of various configs.
Closes #329
=> fix: ignore spaces in comma separated lists configs

src/core/kconf_update/legacy_shortcuts.cpp
This fixes the issue, when the existing shortcuts are overridden.
Make sure that the `~/.config/kglobalshortcutsrc` DOES NOT have the `bismuth_shortcuts_from_kwin.upd:bismuth-shortcuts-from-kwin` element in `[$Version] update_info` section.
Bismuth old shortcuts exist. New shortcuts are undefined.
1. Reload Script.
2. Old shortcuts are deleted. New are created, and they are identical to the old ones.
Bismuth old shortcuts exist. New shortcuts exist.
1. Reload Script.
2. Old shortcuts are deleted. Only the shortcuts that were empty are overridden.
Closes #343
=> fix(shortcuts_migration): don't override the existing shortcuts

src/kdecoration/decoration.cpp
Added `this`, so that the lambda does not outlive the class.
Closes #379
=> fix: don't crash on color config change

src/kwinscript/driver/index.ts
Currently the signals we're getting from kwin aren't causing us to retile windows when they're moved between desktops or activities. This PR connects the signals so we trigger a retile when either the desktop or activity is changed.
* move a window from the current desktop/activity to a different one
* switch to that desktop/activity
* without this fix, the desktop/activity is not tiled to reflect the moved window
Closes #363
=> fix windows not tiling after changing desktops or activities

README.md
Hi,
I started the process of package review in Fedora for bismuth so we can install directly via "dnf " without adding extra repository.  Once package review is complete I would like to see merge this request merged and replace current readme with official way of installation for Fedora. 
Latest version copr repo : https://copr.fedorainfracloud.org/coprs/g/kdesig/bismuth/
(It will be not update once package pushed to fedora, it is here for testing)
Fedora package review link  : https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2080701
Thank you.
=> docs: official fedora repository installation guide

src/kwinscript/controller/index.ts, src/kwinscript/driver/index.ts, src/kwinscript/engine/index.ts
See #375
Closes #370, closes #374
=> Fix the inability to move windows between screens

README.md
OpenSUSE Tumbleweed now has Bismuth in its KDE:Extra staging repository.
Update to README.md to reflect the new repository for OpenSUSE Tumbleweed.
=> Update README.md to include new Tumbleweed repo
